### ISSUE TITLE
Keep all `wordpress_sites` in one VM

### ISSUE THREAD

**Issue by jasperf** [roots/trellis-cli#520]
### Summary

I wanted to add a subdomain `blocks.imagewize.com` to same Trellis project where I had `imagewize.com`. So I added it using `composer create-project roots/bedrock blocks `. I also adjusted the `wordpress_sites.yaml`

```
# Created by trellis-cli v1.13.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  imagewize.com:
    site_hosts:
    - canonical: imagewize.test
      redirects:
      - www.imagewize.test
    local_path: ../site
    admin_email: admin@imagewize.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
  blocks.imagewize.com:
    site_hosts:
    - canonical: blocks.imagewize.test
      redirects:
      - www.blocks.imagewize.test
    local_path: ../blocks
    admin_email: admin@blocks.imagewize.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
```

I wanted to restart the vm so did `trellis vm start`. But instead of restarting the existing `imagewize.com` virtual machine it created a new machine
```
limactl list
NAME                    STATUS     SSH                VMTYPE    ARCH       CPUS    MEMORY    DISK      DIR
blocks.imagewize.com    Running    127.0.0.1:57764    vz        aarch64    4       4GiB      100GiB    ~/.lima/blocks.imagewize.com
imagewize.com           Stopped    127.0.0.1:0        vz        aarch64    4       4GiB      100GiB    ~/.lima/imagewize.com
....
```
 And that also caused load issues as I guess the Nginx configuration of the existing virtual machine and new one clashed. 

```
cat ~/.lima/blocks.imagewize.com/lima.yaml
vmType: "vz"
rosetta:
  enabled: false
images:
- location: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  arch: x86_64
- location: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img
  arch: aarch64

mounts:
- location: /Users/me/code/imagewize.com/blocks
  mountPoint: /srv/www/blocks.imagewize.com/current
  writable: true
- location: /Users/me/code/imagewize.com/site
  mountPoint: /srv/www/imagewize.com/current
  writable: true

mountType: "virtiofs"
ssh:
  forwardAgent: true
  loadDotSSHPubKeys: true
networks:
- vzNAT: true
containerd:
  user: false
provision:
- mode: system
  script: |
    #!/bin/bash
    echo "127.0.0.1 $(hostname)" >> /etc/hosts
```

But main issue is that I need to be able to run multiple sites on one Trellis setup and so also on one macOS virtual machine.

### Additional context

Also see https://discourse.roots.io/t/trellis-vm-main-domain-subdomain-same-virtual-machine/29340 where I wrote a bit more
