### ISSUE TITLE
Database access command

### ISSUE THREAD

**Issue by retlehs** [roots/trellis-cli#7]
https://github.com/TypistTech/vagrant-trellis-sequel exists for vagrant, but we could also support sequel connections to the remote environments

**Comment by TangRufus** [comment]
To do so, we need a way to _compile_ [`site_env`](https://github.com/roots/trellis/blob/faaf213ae2186c6ccf55159becd8910e20c82bf1/group_vars/all/helpers.yml#L12):
  1. decrypt vault files
  2. combine site_env
  3. handling ansible vaibles, example:
     ```
     vault_wordpress_sites:
       example.com:
         env:
            db_password: "{{ my_prefix }}_dbpassword"
     ```

Any idea how to implement them in golang?
